# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_left
    - joint_right
    - left_front_joint
    - left_rear_joint
    - right_front_joint
    - right_rear_joint
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  []
rover_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  gains:
    joint_1: {p: 10000.0, i: 0.03, d: 2.0}
    joint_2: {p: 25000.0, i: 0.02, d: 5.0}
    joint_3: {p: 30000.0, i: 0.01, d: 2.0}
    joint_4: {p: 25000.0, i: 0.01, d: 1.0}
    joint_5: {p: 10000.0, i: 0.02, d: 1.0}
    joint_6: {p: 100.0, i: 0.02, d: 1.0}

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10


#rover_arm_right_finger:
#    type: position_controllers/JointPositionController
#    joint: joint_right


#rover_arm_left_finger:
#    type: position_controllers/JointPositionController
#    joint: joint_left

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1: {p: 10000.0, i: 0.03, d: 2.0}
    joint_2: {p: 25000.0, i: 0.02, d: 5.0}
    joint_3: {p: 30000.0, i: 0.01, d: 2.0}
    joint_4: {p: 25000.0, i: 0.01, d: 1.0}
    joint_5: {p: 10000.0, i: 0.02, d: 1.0}
    joint_6: {p: 100.0, i: 0.02, d: 1.0}

